(import (scheme file))
(define input (open-input-file "day2.txt"))
(define (string-split char-delimiter? string)
  (define (maybe-add a b parts)
    (if (= a b)
        parts
        (cons (substring string a b) parts)))
  (let ((n (string-length string)))
    (let loop ((a 0)
               (b 0)
               (parts '()))
      (if (< b n)
          (if (not (char-delimiter? (string-ref string b)))
              (loop a (+ b 1) parts)
              (loop (+ b 1) (+ b 1) (maybe-add a b parts)))
          (reverse (maybe-add a b parts))))))
(define inarr
  (map (lambda (r) (map string->number (string-split (lambda (c) (char=? c #\-)) r)))
    (string-split (lambda (c) (char=? c #\,)) (read-line input))))
(define (range first last)
  (if (> first last)
      '()
      (cons first (range (+ first 1) last))))
(define orf (lambda a (if (eqv? a '()) #f (or (car a) (apply orf (cdr a))))))
(define addf (lambda (a) (if (eqv? a '()) 0 (+ (car a) (addf (cdr a))))))
(define (group n lst)
  (if (< n 1)
      (error "group: n must be positive" n)
      (let loop ((lst lst) (m n) (g '()) (gs '()))
        (cond ((and (null? lst) (null? g))
               (reverse gs))
              ((or (null? lst) (zero? m))
               (loop lst n '() (cons (reverse g) gs)))
              (else
               (loop (cdr lst) (- m 1) (cons (car lst) g) gs))))))
(define repetition
    (lambda (a) (let ((stra (number->string a))) (if (apply orf (map (lambda (n) (and (= 0 (modulo (string-length stra) n)) (apply string=? (map list->string (group n (string->list stra)))))) (range 1 (- (string-length stra) 1)))) a 0))))
(define meower
  (lambda (a b) (addf (map repetition (range a b)))))
(print (apply + (map (lambda (a) (apply meower a)) inarr)))
