(import (scheme file))
(define input (open-input-file "day2.txt"))
(define (string-split char-delimiter? string)
  (define (maybe-add a b parts)
    (if (= a b)
        parts
        (cons (substring string a b) parts)))
  (let ((n (string-length string)))
    (let loop ((a 0)
               (b 0)
               (parts '()))
      (if (< b n)
          (if (not (char-delimiter? (string-ref string b)))
              (loop a (+ b 1) parts)
              (loop (+ b 1) (+ b 1) (maybe-add a b parts)))
          (reverse (maybe-add a b parts))))))
(define inarr
  (map (lambda (r) (string-split (lambda (c) (char=? c #\-)) r))
       (string-split (lambda (c) (char=? c #\,)) (read-line input))))
(define (range first last)
  (if (> first last)
      '()
      (cons first (range (+ first 1) last))))
(define meower
  (lambda (a b)
    (if (= (string-length a) (string-length b))
        (if (= (modulo (string-length a) 2) 0)
            (let* ((quot (+ (string->number (make-string (/ (string-length a) 2) #\9)) 1))
                   (lo (quotient (string->number a) quot))
                   (hi (quotient (string->number b) quot))
                   (relo (if (>= (* (+ quot 1) lo) (string->number a)) lo (+ 1 lo)))
                   (rehi (if (<= (* (+ quot 1) hi) (string->number b)) hi (- hi 1))))
                (map (lambda (a) (* (+ quot 1) a)) (range relo rehi)))
            '())
        (append (meower a (make-string (string-length a) #\9))
                (meower (number->string (+ (string->number (make-string (string-length a) #\9)) 1))
                        b)))))
(print (apply + (apply append (map (lambda (a) (apply meower a)) inarr))))
