(import (scheme file)
        (scheme cxr))
(define input (open-input-file "day5.txt"))
(define (string-split char-delimiter? string)
  (define (maybe-add a b parts)
    (if (= a b)
        parts
        (cons (substring string a b) parts)))
  (let ((n (string-length string)))
    (let loop ((a 0)
               (b 0)
               (parts '()))
      (if (< b n)
          (if (not (char-delimiter? (string-ref string b)))
              (loop a (+ b 1) parts)
              (loop (+ b 1) (+ b 1) (maybe-add a b parts)))
          (reverse (maybe-add a b parts))))))
(define read-ranges
  (lambda (acc)
    (let ((line (read-line input)))
      (if (string=? line "")
          acc
          (read-ranges (cons (map string->number (string-split (lambda (c) (char=? c #\-)) line))
                             acc))))))
(define get-range
  (lambda (set elem)
    (if (eqv? set '())
        '()
        (if (and (>= elem (caar set)) (<= elem (cadar set)))
            (car set)
            (get-range (cdr set) elem)))))
(define ranges (read-ranges '()))
(define simplify-ranges
  (lambda (dec acc)
    (if (eqv? dec '())
        acc
        (let ((rgl (get-range acc (caar dec)))
              (rgh (get-range acc (cadar dec))))
          (let ((newl (if (eqv? rgl '())
                          (caar dec)
                          (+ (cadr rgl) 1)))
                (newr (if (eqv? rgh '())
                          (cadar dec)
                          (- (car rgh) 1))))
            (if (< newr newl)
                (simplify-ranges (cdr dec) acc)
                (simplify-ranges (cdr dec) (cons (list newl newr) acc))))))))
(define solve
  (lambda (dec acc)
    (if (eqv? dec '())
        acc
        (solve (cdr dec) (+ (- (cadar dec) (caar dec)) acc 1)))))
(display (solve (simplify-ranges (simplify-ranges ranges '()) '()) 0))
