(import (scheme file)
        (scheme cxr)
        (srfi 69)
        (srfi 132))
(define input (open-input-file "day9.txt"))
(define (string-split char-delimiter? string)
  (define (maybe-add a b parts)
    (if (= a b)
        parts
        (cons (substring string a b) parts)))
  (let ((n (string-length string)))
    (let loop ((a 0)
               (b 0)
               (parts '()))
      (if (< b n)
          (if (not (char-delimiter? (string-ref string b)))
              (loop a (+ b 1) parts)
              (loop (+ b 1) (+ b 1) (maybe-add a b parts)))
          (reverse (maybe-add a b parts))))))
(define read-ranges
  (lambda (acc)
    (let ((line (read-line input)))
      (if (eof-object? line)
          acc
          (read-ranges (cons (map string->number (string-split (lambda (c) (char=? c #\,)) line))
                             acc))))))
(define tiles (read-ranges '()))
(define pairs
  (letrec ((ipairs (lambda (val dec acc)
                     (if (eqv? dec '())
                         acc
                         (ipairs val (cdr dec) (cons (list val (car dec)) acc))))))
    (lambda (dec acc)
      (if (eqv? dec '())
          acc
          (pairs (cdr dec) (ipairs (car dec) (cdr dec) acc))))))
(define dist (lambda (pair)
              (let ((dx (- (caar pair) (caadr pair)))
                    (dy (- (cadar pair) (cadadr pair))))
                (* (+ 1 (abs dx)) (+ 1 (abs dy))))))
(define sorted-pairs (list-sort (lambda (a b) (> (dist a) (dist b))) (pairs tiles '())))
(define list-head
  (lambda (list n)
    (if (= n 0)
        '()
        (cons (car list) (list-head (cdr list) (- n 1))))))
(display (dist (car sorted-pairs)))
